### ISSUE TITLE
Migration from non Fluent to Fluent Site

### ISSUE THREAD

**Issue by MauritzFunke** [dnadesign/silverstripe-elemental#1033]
Hello,
I'm trying to migrate a non Fluent Site to a Site with Fluent enabled.
The problem I have is, that the elemental blocks don't migrate.

**Comment by MauritzFunke** [comment]
Hello, any updates or help?

**Comment by michalkleiner** [comment]
Hi, thanks for taking the time to post to the issue tracker.
The issue tracker is reserved for reporting bugs and we don’t provide support via the issue tracker. There are great [community support options](http://www.silverstripe.org/community/#introduction) where you can get help including [our forum](https://forum.silverstripe.org/), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).
I’ll close this issue now but if you find the problem is within the module itself (and you can provide replication steps), feel free to reopen the issue.
