### ISSUE TITLE
RFC: Move ElementVirtualLinked to its own module

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#105]
Similar to #65, ElementVirtualLinked may not be ideal for everybody. Can it be moved to its own repo?

**Comment by pitchandtone** [comment]
Currently there's a fair bit of functionality within BaseElement in order to make Virtuals work which is why I left it in the module.

Options:
Try split said functionality out (not sure how hard this will be)
Keep most of the functionality on baseElement, but move VirtualElement to another repo (unsure if this is easy either)
Leave as is

**Comment by wilr** [comment]
https://github.com/creative-commoners/silverstripe-elemental-virtual

**Comment by wilr** [comment]
@pitchandtone I don't have create repo rights for dnadesign but I imagine that this will sit on the DNA github long term. Let me know and I'll transfer it across. PR for the main repo coming soon.

**Comment by wilr** [comment]
Done. Put on the main repo https://github.com/silverstripe/silverstripe-elemental-virtual
