### ISSUE TITLE
edit elemental redirecting if CMSPreviewable

### ISSUE THREAD

**Issue by vinstah** [dnadesign/silverstripe-elemental#1076]
Reproduce:

Click on an element to be taken to the edit
Edit page loads and then redirects to Page that is holding the elements making editing impossible

current workaround is disabling previewable by extension

**Comment by michalkleiner** [comment]
Are you on the latest version of the module? Any customisations? I recently fixed an issue relating to preview when using subsites.

We need more info and replication steps, if you can provide that. Thanks!

**Comment by vinstah** [comment]
Hi Michal, 
module version 4.11.2

There is a bit of customisation, unsure how to replicate in another project, what I've found is in an extension PreviewLink() { return null; } still shows the preview but doesn't redirect

**Comment by GuySartorelli** [comment]
The mechanism that triggers the redirect looks for the `x-page-id` and `x-cms-edit-link` meta tags.
There is code in the `ElementalPageExtension` which removes those from the `MetaTags` method via an extension hook when the `ElementalPreview` getvar is in the request:
https://github.com/silverstripe/silverstripe-elemental/blob/4e4cbcb88a512d89fadc0acd683499ace92af3e8/src/Extensions/ElementalPageExtension.php#L82-L99
The `BaseElement` adds that getvar to the request when it generates its preview link:
https://github.com/silverstripe/silverstripe-elemental/blob/4e4cbcb88a512d89fadc0acd683499ace92af3e8/src/Models/BaseElement.php#L769-L788

It seems likely that the redirect still occurring is caused by one of your customisations. Without steps to reproduce the bug in a fresh installation, we won't be able to confirm whether that's the case - much less develop a fix if one is needed.

Can you please try to reproduce the bug in a fresh installation? If you don't have time to do so, it is probably better to just close this issue as my guess right now is it's not a bug in the module itself.

**Comment by vinstah** [comment]
Hi Guy,

will update on a fresh installation sometime soon

**Comment by vinstah** [comment]
Hi, Closing this issue.
I've found 0 issues on fresh install.

on my project it seems to only happen on the HomePage, setting the view mode to edit or preview before editing a element it doesn't redirect

**Comment by thats4shaw** [comment]
@vinstah I just experienced similar behaviour myself on a project and found the cause.  We were partial caching the metatags which caused the same behaviour you described.

Thought I'd mention it incase your home page was being fully cached or something like that.
