### ISSUE TITLE
Add indication of the state of a content blocks (draft/modified)

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#165]
The state of a content block should be communicated through the dot above the block icon (similar to the Files area and site tree icon).
https://invis.io/VMDZ9YAGX#/265320689_Blocks_-_Future_-_Carousel_NTH

There should be text tooltip with the block type and state in text format, which will also be useful for accessibility reasons. Note that the published blocks do not communicate the state through text or visually.
Tooltip examples:
[File block: Modified] [Banner block: Draft] [Content block]

**Comment by flamerohr** [comment]
Check out `VersionedGridFieldState` for a re-useable extension to help

**Comment by jelicanin** [comment]
We made some progress on this issue.

Default view:
![default-view](https://user-images.githubusercontent.com/692844/35877872-daf7102a-0b76-11e8-816e-c4827b99937c.png)

Mouse hover on Published item:
![published-item-hover](https://user-images.githubusercontent.com/692844/35877871-dadb1668-0b76-11e8-9336-1de7055f49c5.png)

Mouse hover on Modified item:
![modified-item-hover](https://user-images.githubusercontent.com/692844/35877873-db199aaa-0b76-11e8-9e16-8e1f162c08a2.png)


Check out details [in our fork](https://github.com/fractaslabs/silverstripe-elemental).
I can make PR if you like it.

**Comment by robbieaverill** [comment]
@jelicanin your changes look good, but it's essentially duplicating what GridFieldVersionedState does when you add it to the GridField.

I've been able to add the status badges reasonably quickly using this component:

![image](https://user-images.githubusercontent.com/5170590/35899836-98287a5a-0c33-11e8-9dd3-f79d756a78ff.png)


We'll need to do something sneaky to the status badge to get it to show up an orange dot on the block icon when it's in a draft/modified state though, since that's not a default behaviour of this component:

* Apply the component to one of the fields in the editor grid
* Give the component a `sr-only` class so that the label is present for screen readers but it doesn't modify the UI (the component doesn't provide any extension hooks, so we may need to overload the component in this module)
* Ideally, add a modifier class to the `elemental-preview__icon` element, e.g. `elemental-preview__icon--modified`
* Define some CSS to add the dot for that class (note there's an existing example in the CMS under the `.cms-tree.jstree .status-modified>a .jstree-pageicon:before` selector, visible in the main site tree)

@clarkepaul do you see any merit in adding a modifier class like this to the silverstripe-admin module, so any font icons can have the modified state applied and have the orange circle added by core, or shall we implement this in this module?

**Comment by clarkepaul** [comment]
@robbieaverill  I think SilverStripe Admin is the place for this to happen (introduc a consistent circular state style) so it can be used in all areas if required. Files (thumbs) and Pagetree icons use that pattern too so it would be good to simplify where possible.

Perhaps its fitting to get this merged as a one off (hopefully with the circle if possible) and then have a separate issue to consolidate the styles? I think you'd be better positioned to make that call though.

**Comment by clarkepaul** [comment]
Ha hadn't refreshed my browser so didn't see this was merged already :)

**Comment by robbieaverill** [comment]
Tasks:

* Investigate how the circle is applied to asset admin
* Determine whether we can re-use it
* Implement it in this module, ideally putting any style modifications necessary into admin before 4.1.0 stable
* If all else fails we can do a "phase 1" which would be adding the "draft"/"modified" labels as per default VersionedGridFieldState (see screenshots above) and do circles in a follow up enhancement issue

**Comment by robbieaverill** [comment]
Asset-admin uses some classes that it owns: `.gallery-item--draft` and `.gallery-item--modified`. We could re-use these, but it wouldn't be semantically correct to do so.

**Comment by flamerohr** [comment]
I recommend grabbing the styles the asset-admin uses and applying it to you own gridfield with the namespaced `.some-block-container .status-draft` rule.

**Comment by flamerohr** [comment]
we could put it in the admin, but are we making it a generic case for all versioned gridfields or only "some" cases?
the some cases could be marked with a specific class perhaps

**Comment by robbieaverill** [comment]
I spoke to @clarkepaul about this earlier, he's in favour of putting it into core (eventually with various size modifiers) if possible. Only really feasible if we can squeeze it into 4.1.0 though

**Comment by flamerohr** [comment]
might be a bit late for 4.1.0, maybe? you know who to talk to for that :D

does that mean all versioned gridfields though?

**Comment by robbieaverill** [comment]
>does that mean all versioned gridfields though?

No! Just a design pattern that is likely to be repeated AFAIK

**Comment by flamerohr** [comment]
ok, sounds good 👍

**Comment by robbieaverill** [comment]
Just spoke to @chillu about getting this into 4.1 and we decided that rather than doing it in a half baked way we should put this into elemental for now and log an issue on admin to add the dot pattern into admin in a flexible way (e.g. size modifiers) so it can be used easily in future

**Comment by robbieaverill** [comment]
PR at #190

**Comment by NightJar** [comment]
Did you add that issue to `silverstripe/admin` @robbieaverill ?
If so could you please create a reference/link here?

**Comment by robbieaverill** [comment]
Not yet, thanks for reminding me
