### ISSUE TITLE
Embedded images in content elements don't automatically publish with the element

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#210]
Versions:

```
silverstripe/recipe-content-blocks        dev-master 86552dc
dnadesign/silverstripe-elemental          2.x-dev 0bbe235
silverstripe/cms                          4.1.x-dev 7dea009
```

Given I:

* Add a content element to a page
* Add some content to that element, including an inline image in the content (which I've just uploaded to do this with)
* Save the content element
* Go back and publish the page

Result:

* Page and elements in page are all published
* Image within content element is still in draft
* Frontend users can't see the image

Expected:

```diff
- * Image within content element is still in draft
- * Frontend users can't see the image
+ * Image within content element is published as well
+ * Frontend users can see the image
```

---

Notes:

* Marked as medium impact because a CMS user can manually publish the image to workaround this issue
* The CMS has some custom handling for HTML embedded images, it possibly isn't being triggered for this level of nesting

**Comment by bummzack** [comment]
I think what you're observing is probably this: https://github.com/silverstripe/silverstripe-versioned/issues/75

**Comment by robbieaverill** [comment]
Yep, nice! 😄

**Comment by pxwee5** [comment]
This applies to $has_one files as well in elements.

**Comment by robbieaverill** [comment]
@pxwee5 for physically related files (and any other objects) you can use the `$owns` config API to have them publish, delete and duplicate with the element

**Comment by robbieaverill** [comment]
Soon the master branch here will require SS 4.2, so we should be able to implement the new changes from https://github.com/silverstripe/silverstripe-versioned/issues/75

**Comment by raissanorth** [comment]
This this not an issue any longer for `dev-master` at `4.x-dev` since a page publish  - which is required to reflect changes made to blocks - saves and publishes all blocks as well as the included files.

To test this I added two content blocks and added images to each via the HTML editor field. The first block I saved, the second block I published.
Then I published the entire page that contains the Elemental Area.

In an incognito window I can see the following:

![image](https://user-images.githubusercontent.com/14869519/47881510-2bb67b80-de8b-11e8-9f40-133b5de68bc5.png)
