### ISSUE TITLE
$db - Field Naming - Content

### ISSUE THREAD

**Issue by mspacemedia** [dnadesign/silverstripe-elemental#245]
Just got caught, I created a new module and named a $db field 'Content' this sent the SS_Viewer templating engine into a tail spin.

**Comment by robbieaverill** [comment]
Hi @mspacemedia, can you please provide the versions of SilverStripe and this module that you're using?

**Comment by bummzack** [comment]
From what I've gathered on slack, this is an SS3 site. And since `Widget` has a `Content` method that renders the template, it'll render recursively, as soon as you put `$Content` into your block template.

So this is actually more of a framework issue with `Widget` and we can all agree that using `Content` as method-name was a poor choice.

**Comment by mspacemedia** [comment]
Indeed bummzack I would have to agree that Widget should be shot for causing the recursion issue!
