### ISSUE TITLE
Save all blocks on page save

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#328]
In-line edited blocks can be saved individual but should be saved (en masse) when a page save is triggered. This would involve either looping through all "dirty" blocks and triggering a save (asynchronously) or creating some form of aggregation tool for multiple `FormBuilderLoader` forms.

I'm not entirely sure on the best approach here.

A/Cs
- [ ] Saving a page with an elemental area will also save all edits to blocks
- [ ] Blocks that have been edited but collapsed without saving are still saved
- [ ] Other page elements save as expected 

Split from #295

**Comment by robbieaverill** [comment]
So (I think) you'd only ever have one block's edit form open at at time.

Is the intended behaviour that when you open block A, change stuff then open block B that the changes to block A should be saved automatically, or stored in the browser in a draft state? If it's the former then this ticket should just be "save the active block on page save" since there'd only be one. If it's the latter then we'll need to be careful that the FormBuilderLoader doesn't overwrite any changes you've made when you reopen the block's edit form again.

**Comment by ScopeyNZ** [comment]
I discussed this with @clarkepaul. You can have multiple in-line edit forms.

**Comment by brynwhyman** [comment]
We need to work out what should happen when an invalid block can't saved alongside a block that can be saved. Valid blocks and page saves, while the invalid block has an error message?

For now, this issue is being updated to develop a POC that attempts asynchronous saving that prevents the full page and containing blocks from being saved if there is an invalid block that can't be saved.

cc @clarkepaul @chillu

**Comment by chillu** [comment]
> For now, this issue is being updated to develop a POC that attempts asynchronous saving that prevents the full page and containing blocks from being saved if there is an invalid block that can't be saved.

I think a page-level save operation should be atomic: Either it saves, or it doesn't (and returns with errors). That should apply to all blocks as well (implemented via database transactions). What's the purpose of "incremental" saving of valid blocks, while not saving invalid blocks? Do you expect the author to abandon the page edit without rectifying any validation errors and attempting another save? 

Regardless of validation errors or not, unsaved changes should prompt a warning when navigating away from an edit form, so we need to ensure this is the case after a page-level save with validation errors in blocks.

Implementation note: Please don't fire off one XHR request per block for this, it'll cause performance issues.

**Comment by ScopeyNZ** [comment]
I've created #367 to actually come up with a solution to this problem. This should be blocked until we have a good direction to take this.

I've removed the A/C:

> - [ ] Develop a POC that attempts asynchronous saving that prevents the full page and containing blocks from being saved if there is an invalid block that can't be saved.

This is really a solution disguised as an A/C anyway - and it's not clear that this would actually be useful work.

/cc FYI @chillu

**Comment by chillu** [comment]
> I think a page-level save operation should be atomic

Note that I've put this stance a bit more into context over at https://github.com/dnadesign/silverstripe-elemental/issues/367#issuecomment-418679345. In short, performance is king, everything else is flexible 🚀

**Comment by clarkepaul** [comment]
I'm hoping we can save what can be saved, leaving only the invalid block/page(s) unsaved, it would be annoying to loose an entire pages work for the sake of one little thing which fails. I would think that showing a notification alert next to the failed item—something to aim for?

**Comment by robbieaverill** [comment]
Done in #439
