### ISSUE TITLE
Unable to upload files inline

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#452]
Running the latest elemental `dev-master f7a4c73826` it is not possible to add a file to a file or banner block through the inline interface.

**Comment by NightJar** [comment]
This issue is two fold:
- New files cannot be uploaded from the user's computer, as the form routing is no longer available since the gridfield is no longer used, and the upload field is not valid on the Page's edit form.
- Files selected to be attached are not saved - UploadField uses `[]` syntax, which may be messing with the way redux form stores state and perhaps muddling the mutation. Avenue of investigation, not clear direction.

***
I'll edit this comment to make more sense later.

**Comment by brynwhyman** [comment]
This relies on #480 before being un-blocked

**Comment by ScopeyNZ** [comment]
Closed by #480 and #456
