### ISSUE TITLE
Inline editable blocks don't respect getCMSValidator

### ISSUE THREAD

**Issue by scott1702** [dnadesign/silverstripe-elemental#517]
Steps to reproduce
- Create inline editable block with getCMSValidator function
```
    public function getCMSValidator(): Validator
    {
        return RequiredFields::create([
            'Title',
        ]);
    }
```
- Add block to page
- Publish page without entering Title

Expected behaviour:
Block doesn't get published due to required fields not being filled.

Actual behaviour: 
Block gets published with required fields not filled.

I feel like this is fairly high impact as developers cannot rely on certain fields being filled out due to this issue.

**Comment by robbieaverill** [comment]
This is because the publish actions doesn't save first, it publishes the latest saved draft version so there's no need to validate it. 

We have a ticket to track that as an enhancement, since it would make sense to save and publish like the CMS does when you hit "Publish." See https://github.com/dnadesign/silverstripe-elemental/issues/470
