### ISSUE TITLE
Cannot add new block inline with subsites

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental#526]
**Version: CWP 2.2.x-dev**

* Create some subsites
* Switch to a subsite that isn't "Main site"
* Create a new Blocks Page
* Try to add a content block to it

Expected: should add a new content block

Actual: nothing happens

GraphQL response returns successfully (it would seem) but with no records in it.

**Comment by ScopeyNZ** [comment]
If I _don't_ use the elemental subsites compatibility module it works fine for me. I'm not sure what the compatibility module it doing to be honest. It's putting `SubsiteID` on `BaseElement` but I don't understand why? We have an area per page which'll sort Subsites I think?

**Comment by robbieaverill** [comment]
I'm not really sure either. I think it's there to support the [elemental-virtual](https://github.com/dnadesign/silverstripe-elemental-virtual) module functionality, where you could use a block on multiple pages via an unversioned many many. Since SilverStripe Ltd doesn't support that module, perhaps we could remove the subsites compatibility module from the content blocks recipe and CWP kitchen sink, and add a note to the virtual module suggesting you install the subsites compat module if using virtual elements on a project with subsites

**Comment by ScopeyNZ** [comment]
Yeah I didn't get a chance to check out that module today or play around with this some more to figure out its purpose. I'll try to get some time before the beginning of next week.

Otherwise I agree with removing it. Currently it works better without it than with it (in the context of subsites).

**Comment by brynwhyman** [comment]
Given that initial investigations seem to imply that this issue is being caused by the `dnadesign/silverstripe-elemental-subsites` module; or rather that subsites and elemental are compatible without the inclusion of this module, I'm inclined to reduce the impact.

`dnadesign/silverstripe-elemental-subsites` already isn't included in the `silverstripe/recipe-content-blocks` recipe, so no need to remove it. We should confirm that it's sole purpose is to support the [elemental-virtual](https://github.com/dnadesign/silverstripe-elemental-virtual) module functionality. I'll raise an issue within that repo to capture that.

**Comment by robbieaverill** [comment]
We've removed it from the recipe - closing
