### ISSUE TITLE
Restrict v4.0 to SS4.3

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#529]
From @robbieaverill :

When running elemental 4.0 (react 15) on SS 4.4 (react 16 backend) I'm getting an undefined on PropTypes from react, even though we import PropTypes from our own version of react in elemental... my initial suspicion is that webpack-config is loading react from admin instead, and that we'll need to restrict this version of elemental (4.0) to SS 4.3 only and start a new 4.1 for SS 4.4

**Comment by ScopeyNZ** [comment]
The alternate option is that we quickly convert the 4.0 branch to use the stand-alone `PropType` library before we tag stable. We can still leave it on React 15.

I think that'll resolve the issue?

**Comment by robbieaverill** [comment]
It would resolve _this_ issue, and would be quick and easy to do, but it wouldn't guarantee that we don't have other problems if my initial suspicion is correct

**Comment by unclecheese** [comment]
Yeah, prop-types should really be the only massively fatal error you see. In fact it may be the only one. My advice would be to upgrade to use the prop-types library. Then give it a reasonable window of time to troubleshoot in React 16. I suspect you’ll be fine. 

If it turns out to be a yak shave, just commit the upgrade to prop-types, as it’s entirely backward compatible, and lock to 4.3. 

We should be using prop-types anyway. Can’t hurt to do the upgrade now.

**Comment by robbieaverill** [comment]
Fixed with #534
