### ISSUE TITLE
Elemental 3 is incompatible with SilverStripe 4.3

### ISSUE THREAD

**Issue by NightJar** [dnadesign/silverstripe-elemental#554]
This is technically a backwards compatibility break in core, but can probably be fixed by a patch release of Elemental 3 - It seems that the issue may lie with a GraphQL query or scaffolding.

Caution should be taken to not make Elemental 3.x incompatible with SilverStripe 4.2, which would be a problem.

@brynwhyman @chillu

**Comment by chillu** [comment]
Needs more detail

**Comment by NightJar** [comment]
Sorry.
Steps to recreate:
- Have a site with Elemental 3 running SilverStripe 4.2
- Change the composer.json to run SilverStripe 4.3.0
- `composer update`
- dev/build
- log in to `/admin`
- open a page with an ElementalArea
- Add a new element of any type
- Edit the content of this new Element
- Save that element.

See: "Left" remains a menu that can be used, but "Main" is a big nothing.

Reload the page
See: No new element.

**Comment by chillu** [comment]
OK, I'll leave it with Creative Commoners to figure out if this needs any action in core, and if we've broken some implicit semver promises there.

**Comment by NightJar** [comment]
I think this is a question for the context @robbieaverill and @ScopeyNZ have. Perhaps @cheddam would like to weigh in also?

**Comment by ScopeyNZ** [comment]
I think it is something we're noticing with modules that have a GraphQL dependency. The requirement to make it compatible with 4.3 (and GraphQL 3.0) is to alter the config so that it's within a named schema (ie. admin). However this makes it incompatible with 4.2 (GraphQL <3.0).

So "a fix" is to have:
1) a way to have config apply per core version (probably far fetched)
2) have some way to update GraphQL < 3 so that it can understand multischema and make that a requirement (`graphql: ^2.x || ^3`) - i.e forwards compatibility
3) Update GraphQL 3.x to assume un-namespaced schema is within the `admin` schema - perhaps based on some config variable in the same section - i.e backwards compatibility.

We've already had a complaint about the next `3.x` of elemental only supporting `4.3`: https://github.com/dnadesign/silverstripe-elemental/pull/552#issuecomment-448394902

I think it's fair to say this is pretty close to (if not already) a semver break.

**Comment by chillu** [comment]
I'm sorry, but if you're updating to a new major release of Elemental, I think it's reasonable to expect that you're also able to update to a minor release of the underlying framework recipe. We should make this relationship quite clear in the changelogs for Elemental of course. 

Maybe this means that minor releases of Elemental shouldn't bump major versions of dependencies (not sure if we're doing that), since I could understand the surprise by developers looking into upgrades.

In the end, semver is a useful tool, but it can't stop us moving forward before SilverStripe 5.x is released in 2020. We should strive for backwards compat in the "foundational" modules (core recipe), but the reality is that we can't call GraphQL "API stable" until 2020 yet. I'd expect that we should be able to perform the majority of API changes in that module in a backwards compatible manner, but I'm not comfortable committing to do this for *all* API changes.

@unclecheese Can you please look into Guy's comment above and open a GraphQL backwards compat ticket with `impact/high` if there's anything we can do?

**Comment by Cheddam** [comment]
The issue here isn't when a user upgrades to a new major release of Elemental, it's when they upgrade to a new minor release of SilverStripe. Elemental 3 was released before SilverStripe 4.3, which means there are likely projects that were created in the meantime that will get tripped up by this if they try to bump their dependencies (assuming `"silverstripe/framework": "^4.2"` and `"dnadesign/silverstripe-elemental": "^3.0"`).

I think the argument that "if you can adopt major releases of modules, you can adopt minor releases of core" is fine, but the reverse argument - that "if you can adopt minor releases of core you can adopt major releases of modules" - doesn't hold water.

GraphQL's API instability makes sense right now, and isn't a problem by itself, but this issue makes it clear that its instability isn't completely isolated. Monitoring and mitigating this until 5.x feels pretty important to me.

Focussing back on this particular issue: I've discussed with @ScopeyNZ and @NightJar, and we should be able to shift to applying _both_ versions of the schema configuration in modules to resolve compatibility. It'd still be better to add support for the legacy config in GraphQL 3.x, but we now have a workaround if that's not viable.

**Comment by ScopeyNZ** [comment]
> we should be able to shift to applying _both_ versions of the schema configuration in modules to resolve compatibility. 

PR @ #557

**Comment by robbieaverill** [comment]
Yeah I think this is an example of where we're shipping new features in major release bumps in core (graphql 2 to 3 to 4) in a way that isn't backwards compatible, which isn't surprising since it's a major version bump. It's difficult to constrain things like elemental 3.0 to limit their SilverStripe version ceiling (because you can't change dependency constraints in tags that have already been released) so we end up releasing new versions of the modules with new minimums and updated code in them.

#557 is a good fix - it's non-breaking compatibility for both versions. Hopefully we don't find examples where this isn't possible in future!

**Comment by robbieaverill** [comment]
Fixed with #557
