### ISSUE TITLE
allowed_elements no longer restricts the elements available on a given page. 

### ISSUE THREAD

**Issue by Kethatril** [dnadesign/silverstripe-elemental#556]
As of 4.0.0 allowed_elements, and probably disallowed_elements no longer work.

In 4.0.0-beta1 the elementTypes array was retrieved from the data-schema attribute on the element. This returned the correct list.

With 4.0.0 elementTypes is retrieved by using `Config.getSection('DNADesign\\Elemental\\Controllers\\ElementalAreaController')` which returns all available element types (as seen in ElementalAreaController getClientConfig)

**Comment by ScopeyNZ** [comment]
Ah yep I can see how that'll happen.

The hard bit is that the area should still be aware of all element types, in case the `allowed_elements` configuration has been changed. You're right that the options provided in the "Add Block" popover should be limited by the configuration though...

The fix will probably look something like adding the configuration back to `getSchemaDataDefaults` on the field, and updating the React code to use that option when deciding what block types to put in the "Add block" button. Is this something you might be interested in giving a go? I'm happy to help out and I'm available on the community slack (`@Scopey`). Otherwise I'll add it to my never-ending list - hopefully I'll get time soon into the new year. 

Thanks for the bug report.

**Comment by Kethatril** [comment]
I'll see what I can do. Probably won't get to it til the new year, but we are using allowed_elements so I'm invested in getting it fixed 😄 .

**Comment by ScopeyNZ** [comment]
Fixed in #570 🙂
