### ISSUE TITLE
Elements in "add block" popup aren’t in alphabetical order

### ISSUE THREAD

**Issue by kinglozzer** [dnadesign/silverstripe-elemental#567]
SilverStripe 4.3.0 / Elemental 4.0.0

<img width="359" alt="screenshot 2019-01-16 at 12 16 56" src="https://user-images.githubusercontent.com/1655548/51248623-a1a98980-1988-11e9-9e67-3b0756709da4.png">

Even if `sort_types_alphabetically: true` is set explicitly (I believe it’s the default anyway), the elements appear to be sorted by PHP class name and not title. I guess the list is fetched via graphql, as `ElementalAreasExtension::getElementalTypes()` still seems to output them in the correct order

I know it should also possible to define a custom order with `sort_types_alphabetically: false` and the `available_elements` setting, I’ve not tested the ordering with that.

**Comment by robbieaverill** [comment]
Quick investigation, I've written some tests for `ElementalAreasExtension::getElementalTypes()` (see e80875f), but here's the problem:

* `elementTypes` prop is gathered from schema config
* This is generated by `ElementalAreaController::getClientConfig()`
* `$clientConfig['elementTypes'] = ElementTypeRegistry::generate()->getDefinitions();`
* `ElementTypeRegistry` doesn't use `ElementalAreasExtension::getElementalTypes()` to generate the list of available elements, which also includes the sorting. It has its own logic

I would've made a quick patch for this, but `getClientConfig()` should be stateless, and `ElementalAreasExtension::getElementalTypes()` needs to know about its owner in order to get the config on a per-page type basis.

cc @ScopeyNZ

**Comment by ScopeyNZ** [comment]
Yeah so the idea is that `getClientConfig` is stateless and always contains all element types. The add block popover then limits that list with schema configuration on the `ElementEditor` component. I guess we should sort based on that too.

This allows for instances where developers may have disallowed elements on an area that already contains a disallowed element (otherwise everything breaks).

**Comment by ScopeyNZ** [comment]
Ok that's not happening 😂 

I assume allowed/disallowed elements are not working too.

**Comment by ScopeyNZ** [comment]
FYI This should've been resolved in #570 but I haven't had the opportunity to double check yet.

I'll leave it open until I get the chance to check it.

**Comment by robbieaverill** [comment]
I tested it in #570, resolved! Thanks @Kethatril!
