### ISSUE TITLE
Blocks which are "Untitled" appear in campaigns without any label

### ISSUE THREAD

**Issue by clarkepaul** [dnadesign/silverstripe-elemental#574]
If a block is newly created it gets a default "Untitled" as the title of that block. That title then needs to carry on through to other sections like the Campaigns area even if its using the placeholder title.
This issue also exists in the Campaigns section
 https://github.com/silverstripe/silverstripe-campaign-admin/issues/129

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-campaign-admin/pull/171

Note: solved at a 'campaign admin' rather than an 'elemental' level, meaning that any item in a campaign (not just content blocks) with a blank title will display "Untitled"

The only other place I could think of where this is relevant is the used on table, though there's a already a PR to show "(Untitled)" there too https://github.com/silverstripe/silverstripe-admin/pull/1083

@clarkepaul Would you prefer the text on these 2 PRs to be:

Untitled

or

(Untitled)

?

**Comment by clarkepaul** [comment]
@emteknetnz can't these just be carried through from the block titles, and whatever structure they use? 
It would be weird to fix the empty title in the campaigns view to something which isn't presented to the user in the page view (they should be the same). 

Also considering there will be future changes... if any changes happen to way we use empty titles on blocks that title should feed through to other areas of the CMS. On a block you shouldn't be able to save it without the title being applied (placeholder or custom). In the page view, if the system has applied the title then we show it as italics but if a user has edited it it then becomes a standard title.

**Comment by emteknetnz** [comment]
@clarkepaul so you'd like it to say "Untitled Content block" ?

![image](https://user-images.githubusercontent.com/4809037/90462236-83a39c80-e15c-11ea-8069-7a25ddfccb14.png)


>> On a block you shouldn't be able to save it without the title being applied (placeholder or custom)

That's would be a change from the current behavior, right now you can most save a Content Block without a title.   The placeholder text "Untitled Content Block" is not saved to the database

**Comment by clarkepaul** [comment]
If we don't currently save it then that is the change that I'm asking for, as I can't think of a better alternative, open to suggestions though. 

We could replicate the same functionality of adding a placeholder title when viewed in Campaigns but that doesn't scale well to things like History Snapshots etc. I'd expect to pull it through to wherever it needs to go. 

So if the placeholder title is replaced by an actual database title, can we somehow indicate that it hasn't yet been edited (is default) and keep the same look as we currently have within blocks? e.g. italics, light colour.

This changes the scope of this issue I guess.

**Comment by emteknetnz** [comment]
Yes it changes the scope significantly

For now, are you happy that things without titles just say "Untitled"?

**Comment by clarkepaul** [comment]
Yup, that's better than nothing thanks. 
So does that then apply to anything in a campaign which has no title or just blocks? e.g. is it scalable to other content types when introduced like gridfield items, pages

**Comment by ScopeyNZ** [comment]
We didn't save "Untitled Content block" into the title field, because then we can't actually tell if they purposefully named it that, or simply left the field blank. I think the way it's done now is correct, an empty title can be saved - and that's how it's saved in the DB. The UI should be responsible for putting in a consistent placeholder when there's no title.

This is how we can put in the italicised title - because we know it's actually empty and we're just displaying a placeholder.

If we were full React, this could be as simple as a `BlockTitle` component that does everything for you, and we use that everywhere, but it's considerably more awkward in its current state.

**Comment by clarkepaul** [comment]
I was hoping to get a consistent placeholder in all scenarios for items. Thought maybe there could be something to say whether it's the placeholder (true, false). Either way using just a simple "Untitled" is going to have to do for now. Might make it simpler if "Untitled" was then used everywhere for any content type, with the down side of no differentiator of content types or distinguishing one item from another.

**Comment by ScopeyNZ** [comment]
I think it's a bit awkward for the developer to handle having a title that may or may not be empty, and a boolean (checkbox) that says whether the empty or present title should be considered "untitled". I'm totally on board with an effort to make "untitled" on any content type a consistent UX experience, but I really don't think that's a concern of the data model in the CMS. It just makes it more confusing for the developer, and more difficult with versioning (of both content and the installed CMS version).
