### ISSUE TITLE
Unable to highlight text areas / other fields in inline editing mode

### ISSUE THREAD

**Issue by torleif** [dnadesign/silverstripe-elemental#575]
When you expand an element in inline editing mode, and try to highlight text inside the field, it causes the element to re-render:

![output](https://user-images.githubusercontent.com/67215/51511418-1b001b00-1e66-11e9-97ec-eac816569d77.gif)

and you cannot highlight the text. 

The react-dnd library needs to disable drag-and-drop when an element is expanded.

**Comment by ScopeyNZ** [comment]
Ah yep. I think a preferred fix would be to just not trigger a drag on events that target the form. We still can support opened blocks being dragged about by the header (or "drag handle").

**Comment by robbieaverill** [comment]
This is a bug with react-dnd, and can be tracked here for progress: https://github.com/react-dnd/react-dnd/issues/438

**Comment by robbieaverill** [comment]
That being said, we could probably fix this by making the `ElementHeader` the draggable part, rather than the entire `Element` which also incudes the `ElementContent` component. This would only change functionality when the element is expanded, and would mean you can't drag from anywhere inside the form itself, only the heading. I think this would be fine myself, especially since we show a drag handle which should tell users to drag from that area anyway.

I had a quick go but ran into an issue with the drop target detection being slightly out and a GraphQL error with a missing argument. I don't have enough context to fix this quickly so probably better for @ScopeyNZ or @NightJar.

**Comment by robbieaverill** [comment]
Fixed with #610, nice one @ScopeyNZ.

If anybody has extended the `Header` React component in their own code and overloaded it with Injector, be aware that it now has a couple of new required props. We think it's justified to merge this change into 4.0.x right now to fix this bug, and see it as a reasonably low likelihood that anyone has actually done this.
