### ISSUE TITLE
V4: getSummary() doesn't use current member's preferred locale

### ISSUE THREAD

**Issue by wernerkrauss** [dnadesign/silverstripe-elemental#577]
I'm on SS4.3 with Elemental 4.

In a gallery block I have a method for creating a Summar (number of images in the gallery)

```
    protected function provideBlockSchema()
    {
        $blockSchema = parent::provideBlockSchema();
        $blockSchema['content'] = $this->getSummary();
        return $blockSchema;
    }

    public function getSummary()
    {
        $template = SSViewer::get_templates_by_class(static::class, '_Summary');
        $summary =  $this->renderWith($template);
        return $summary->RAW();
    }
```

The template looks like:

```
<%t MyNamespace\Gallery.SUMMARY 'One image|{count} images' count=$GalleryImages.Count %>
```

When my admin user has preferred locale "de_DE" it doesn't get translated, cause the current locale during the graphql call to get all blocks is set to "en_US" - I didn't set the default locale in my project yet but that should not matter as different backend users might have different locales set.

If I set the locale manually in my getSummary() method it translates fine.

Is this a bug in Elemental or do I have to switch locales in my getSummary() method? It seems like labels for cms fields are translating fine. How is it handled there?

**Comment by ScopeyNZ** [comment]
Yeah this is an interesting one. When developing we expected the "summary" to contain something based on the content of the block - ie. the first line (or so) of the content saved in the block.

In most cases we expect block developers to extend the React code when they want to make more custom summaries. However after looking over it I can see that this isn't as easy as it should be. I've raised an issue to cover this: https://github.com/dnadesign/silverstripe-elemental/issues/582

Aside from that I'll close this issue with the following answer:
- getSummary is expected to generate a simple string. Nothing translates it because we anticipate that it's generated from saved content.
- You're welcome to do your own translation in getSummary - using templates like you have done is fine but you could also use `_t()` instead
- The other recommendation for developers who want to theme how blocks are shown on a page is to extend the React code - specifically the `Summary`, `Content`, or `Element` components.

To put some code to the "you could use `_t()`" point:

```
public function getSummary()
{
    return _t(static::class . '.SUMMARY', 'One image|{count} images', ['count' => $this->GalleryImages->count()]);
}
```

**Comment by wernerkrauss** [comment]
@ScopeyNZ yup, tried _t() directly in php code, but that didn't work either, cause it falled back to default site locale, not to user's backend locale.

Only wrapping in `i18n::with_locale(Security::getCurrentUser()->Locale, ...)` did the trick
