### ISSUE TITLE
[Performance] Use DataObject::get_by_id() to fetch elements’ ElementalArea

### ISSUE THREAD

**Issue by kinglozzer** [dnadesign/silverstripe-elemental#648]
I’ve noticed that on a page with a lot of elements, there are a number of repeated database queries triggered by `BaseElement::getPage()`. They’re cached against each element, but that still means one call per element when the parent is always going to be the same.

Using the following instead of calling `$this->Parent()` directly saves those repeated lookups (and probably means we could remove `$this->cacheData['page']`):

```php
// Replace...
$area = $this->Parent();

// ...with
$class = DataObject::getSchema()->hasOneComponent($this, 'Parent');
$area = DataObject::get_by_id($class, $this->ParentID);
```

**Comment by ScopeyNZ** [comment]
Sounds good to me! Want to make a PR?

**Comment by michalkleiner** [comment]
Would it possibly be better to have a method getAreaHolder or something like that and stick that code there, so it will cache it for you?
It's one call instead of two and easier to remember. If it's promoted through the existing blocks it might become adopted quite fast. Otherwise people won't know why they need to use 2 long lines to gain performance.
Or, hijack the __call or __get to still use `->Parent()` but leverage the caching there?

**Comment by ScopeyNZ** [comment]
> have a method getAreaHolder

This is something that has come up before - if not on this repo, somewhere on Slack or within the community. This makes a lot of sense. Areas aren't necessarily limited to a page. We missed our opportunity to remove this API in 4.0 but I'll be happy to field a PR that deprecates `getPage` and replaces it with `getAreaHolder`.
