### ISSUE TITLE
Value lost in date field after publishing the page

### ISSUE THREAD

**Issue by ScopeyNZ** [dnadesign/silverstripe-elemental#649]
Latest version of Chrome on MacOS- Version 73.0.3683.86 (Official Build) (64-bit)

The updated value is saved, but the update is not shown when you reopen the block after publishing the page. Instead, it shows the previous value of the date field. 

Even if you publish the block before you publish the page the value displayed is wrong when you reopen the block.

![Mar-24-2019 16-02-18](https://user-images.githubusercontent.com/2531109/54885839-aab64b80-4e4e-11e9-941b-211225f148ce.gif)

_Originally posted by @tomstgeorge in https://github.com/dnadesign/silverstripe-elemental/issues/631#issuecomment-476000288_

**Comment by ScopeyNZ** [comment]
This ended up being another admin specific issue: https://github.com/silverstripe/silverstripe-admin/pull/908

**Comment by robbieaverill** [comment]
Fixed with https://github.com/silverstripe/silverstripe-admin/pull/908. In order to pull in this fix for affected projects using elemental, you will need to be using SilverStripe 4.4.x (or CWP 2.3.x) and will need to either pull in silverstripe/admin 1.4.x-dev, or wait for a new version of that module to be released after time of writing this comment.
