### ISSUE TITLE
Action menu items aren't keyboard accessible

### ISSUE THREAD

**Issue by brynwhyman** [dnadesign/silverstripe-elemental#677]
### Description
While I can use my keyboard to tab to a block and open the action menu, it is not possible to select any of the action options, i.e save, publish, etc.

### Expected behaviour
I can use my keyboard to navigate and select actions such as 'Save' or 'Publish' for a block.

### Versions affected
I've experienced this with `4.1.x-dev 37af945`

It seems to be a regression as this was working fine in `4.0.3`

**Console errors:**
Seen when first expanding the block with a keyboard action:
`Assertion failed: Input argument is not an HTMLInputElement`
`Uncaught TypeError: Cannot read property 'type' of undefined
    at e.setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)`

**Comment by brynwhyman** [comment]
A behat test seems worthwhile to avoid this regressing again

**Comment by robbieaverill** [comment]
This is working correctly for me on 4.1.x-dev bc9043a5f2b5b4f0dbe4968dde8b770f55cf86cd (no code changes between these commits). I'm using Chrome 75 on Mac. Tested with tabs into the menu after pressing enter to open it, as well as arrow keys to navigate its options.

What were you using to reproduce this issue?

FWIW this may have been a change in the admin module in the time that this issue was raised to now.

**Comment by NightJar** [comment]
Also testing using bc9043a5f
I can tab to, open, and select items in the menu.
At first there was a little confusion between pressing enter and using the space bar to select items
- enter is non-standard, using it will always open the content edit form for the block
- space is the standard, using this everything works fine (I can load both content and settings forms)
- arrow keys to navigate the menu once open also work (as opposed to tab/shift+tab)

https://gfycat.com/poshcalculatingarachnid
