### ISSUE TITLE
Disable Cascade-publishing of Element in ElementalArea

### ISSUE THREAD

**Issue by Xarinor** [dnadesign/silverstripe-elemental#681]
In a current project i need to allow sorting Elements inside a Elemental area where unpublished elements need to stay unpublished.

Is it possible to remove cascade publishing trough $owns on the Page or ElementalArea by configuration or is there a workaround?

Greetings
Xari

**Comment by robbieaverill** [comment]
Hi there, since it is defined as an array without keys, you cannot remove it with YAML. You can use Config::modify()->set() in a config.php dile to remove it at runtime though, which would put the publishing burden onto individual elements. Ensure to remove other cascading API configuration as well if you don’t want them.
