### ISSUE TITLE
make all versions inline editing

### ISSUE THREAD

**Issue by sunnysideup** [dnadesign/silverstripe-elemental#746]
We have used Elemental a lot and for some reason, not sure why (sorry no time to work out why), we hardly ever have the inline editing available to us as it does not work with a raft of form fields (AFAIK). 

This makes the interface rather cumbersome as you have to go in and out of elements and feel kind of lost of where you are. Where you are becomes a real intellectual challenge (i.e. you can look at breadcrumb, etc... to rationally work it out) rather than a tactile / `I can look out of the window and see where I am` kind of experience.  It feels like navigating through a mall. 

This UI also means that there are a lot of clicks to get things done.

I really hope this can be improved (e.g. make inline editing available for all elements, no matter what).

**Comment by ScopeyNZ** [comment]
In-line editing is available for any element that uses default CMS form field, except GridField. If you use any other form fields outside of the core set they need to have a React renderer, as forms are generated by JS rather than PHP. A lot of community form fields don't have this (yet), and neither does GridField (yet). Please raise issues on modules that provide specific element types about making them in-line editable, rather than here. GridField is a major blocker here, you can track progress on that here: https://github.com/silverstripe/silverstripe-admin/issues/463

I know (unfortunately) that some have opted to globally disable in-line editing to allow the user a consistent experience. This essentially reverts the UX to what we had in Elemental 3.

**Comment by sunnysideup** [comment]
Thank you for your quick and detailed reply. Much appreciated.

Is there no way that we load the non-React forms inline? Because if even gridfield is not react ready what hope do we have for the 100s of other form fields out there?

**Comment by ScopeyNZ** [comment]
> Also, I will have look how to make fields "react ready". I wish I knew how to do this.

I agree this is definitely a source of pain for the community right now. I don't have much time to contribute to SS right now but I'd love to make this clearer, and if you would like to let me know (maybe over Slack) how you find this experience I'd love to hear about it.
