### ISSUE TITLE
New React UI is slow

### ISSUE THREAD

**Issue by sunnysideup** [dnadesign/silverstripe-elemental#747]
I noticed that in the CMS, the Graph QL call is only made AFTER "document ready".  This means that there is a significant delay in getting the elements for the Elemental interface (you can  see them load after the CMS has been loaded).

I would suggest that someone smarter than me, works out a way to preload the data for the Elemental React component, well before the the "document" is ready or that, for example, the Data for the Elements is included in the div where the Graph QL Elemental Editor will be loaded. 

Right now, the overall UX for the Elemental Editor is not great. I have had several clients complain on how slow it is, etc... It seems to me that preloading the data for the initial load of a page for the Elemental Editor(s) would offer a significant step forward.

**Comment by ScopeyNZ** [comment]
The overall UX is not great - only because you're finding it slow? That's fine, just want to clarify that this is your only complaint.

In the long term this should be solved by not actually navigating around as more is moved to React. Right now, `pjax` does a pretty good job of making it appear faster.

Currently the waiting for document ready requirement is there so we can give client code the right amount of time to extend the UI. You can manipulate the GraphQL query on the client side, for instance. There's not really any solution here I can think of, but this would be an issue for the `admin` repo anyway.

Without any specific other bugs to point out, I'm going to close this now, but feel free to continue the discussion here, or alternatively there are great [community support options](http://www.silverstripe.org/community/#introduction) where you can discuss this including [our forum](https://forum.silverstripe.org), [Stack Overflow (remember to tag as silverstripe)](http://stackoverflow.com/questions/tagged/silverstripe) and even [Slack](http://silverstripe.org/slack).

Sorry we can't be of more help and good luck resolving your problem!

**Comment by sunnysideup** [comment]
Thank you for your quick and detailed reply. Much appreciated.

`The overall UX is not great - only because you're finding it slow? That's fine, just want to clarify that this is your only complaint.` 

the UX is better than most other modules, but as a cornerstone of the SS CMS, I feel it should be better (I have even been told that the WordPress equivalent "Gutenberg" is better). 

Here are a few things that I would like to help make better: 

- loads only after CMS is fully loaded.

- some confusion about what happens when you add a new element - e.g. no one creates a page in reverse order so why do new elements go to the top?

- hard to see what type elements are (need to hover AFAIK)

- lots of clicks when React form fields are not available
 
`Currently the waiting for document ready requirement is there so we can give client code the right amount of time to extend the UI. You can manipulate the GraphQL query on the client side, for instance. There's not really any solution here I can think of, but this would be an issue for the admin repo anyway.`

I have raised it with `Admin` module as well.  Can we not simply add the default data into the "div" so that it already has something to go by and if the actual document ready query is different then run this also? I am sure that 90% of the time, we can guess the GraphQL query for the Elemental Editor.
