### ISSUE TITLE
Element summary prevents element from loading if spacial characters are present

### ISSUE THREAD

**Issue by alex-dna** [dnadesign/silverstripe-elemental#781]
Hi,

we've noticed that adding an ElementContent with Chinese characters in the HTML prevents the element from showing in the elements list in the CMS.
The loader never disappears and a console error stating the json is invalid appears.
Possibly the react/ajax request is not supporting utf8 characters in the schema.

Tested with the following text:
充美好实的一天

Thanks.

# Pull Request
* [x] https://github.com/silverstripe/silverstripe-framework/pull/9584

**Comment by brynwhyman** [comment]
Bumping to impact/critical as there's effectively no workaround for this.

**Comment by mfendeksilverstripe** [comment]
I can confirm that this is an issue. Adding more information.

## Encoding

make sure your encoding is properly set. Is is recommended to drop your database and rebuild it as `dev/build` doesn't update database and table char-sets, only fields.

```
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
```

## Test setup

Elemental module with no modifications. Using the out of the box content block (`ElementContent`) which is inline editable.

* create a block page
* create a content block
* add some non-latin characters into the content area `玩游戏以及观看视频和电视节目的好地方。但它也会对我们的儿童和青少年产生不利影响。`
* save you block
* attempt to load page edit form

### Expected behaviour

Elemental area is properly loaded so user can view / inline edit the blocks.

**Comment by maxime-rainville** [comment]
I think I've narrowed the problem to this line. https://github.com/dnadesign/silverstripe-elemental/blob/49866952a5f4f4c961a7be0a89e5250c278a15af/src/Models/ElementContent.php#L44

Looks like the Summary there is doing something this string that confuses GraphQL. I tried running this bit of code.
```php
var_dump('充美好实的一天');
var_dump(DBField::create_field('HTMLText', '充美好实的一天')->Summary(20));
```

That's what came out.
```
ElementContent.php:49:string 'åç¾å¥½å®çä¸å¤©' (length=21)

ElementContent.php:50:string 'å

ç¾å¥½å®çä¸å¤©' (length=21)
```

If I comment out the statement and replace it with `return '充美好实的一天';` it works fine.

**Comment by maxime-rainville** [comment]
This line in `DBHTMLText::Plain()` is the problem I think.
```
$text = preg_replace('~(\R){2,}~', "\n\n", $text);
```

If you comment this out, "充美好实的一天" gets outputted properly.
