### ISSUE TITLE
Add helper methods for ElementalArea cache invalidation

### ISSUE THREAD

**Issue by dnsl48** [dnadesign/silverstripe-elemental#795]
## Problem statement
Implementing caching strategies for a page containing an ElementalArea is hard.

## Description
The key problem is we have no API providing any info from blocks within the area if they can be cached or not. If we loop through the elements manually and check them for cacheability, we cannot do that in a generic way, since BaseElement has no API for providing any info about its cacheability.

## Proposal
We introduce several cache invalidation helper methods to ElementalArea and BaseElement.
  - `public ElementalArea::isCacheable() : bool`
  - `public ElementalArea::getCacheKey() : string`
  - `public BaseElement::isCacheable() : bool`
  - `public BaseElement::getCacheKey() : string`

Both `isCacheable` and `getCacheKey` are context sensitive and should be calculated in runtime (non-static implementations) depending on the particular data rendered and business-logic in the module.

To maintain backward compatibility, by default `isCacheable` would return `false` and `getCacheKey` would return a random value. Any block that may be cached should provide its own implementations for both methods.

Since both methods may add some overhead (e.g. extra SQL queries) on every request, I suggest we leave them `opt-in`. That means we do not implement any default OOTB caching. Instead we should provide the documentation necessary to implement proper caching, utilising the API suggested.

## PRs
 - https://github.com/dnadesign/silverstripe-elemental/pull/797 (PoC / Draft)

### Pros:
 - Simple and generic (2 methods with 10 and 7 lines of code accordingly)
 - Applicable for at least template partial caching and HTTP caching. May or may not be useful for other caching types and strategies.
 - Introduces conventions for implementing caching in blocks consistently (atm every block has to have its own adhoc APIs for caching and cache invalidation)
 - Gives people an actual working feature, ready for use and with safe defaults (can be used without too much thinking about how caching works)

### Cons
 - Extra feature to maintain
 - The API doesn't do much on its own. Still have to implement caching in every block to have any performance benefits
 - The API mingles with model, lacking separate clear interfaces (no separation of concerns). Introducing separate caching components makes little sense in this module (that ideally should be in the framework, but this is not feasible)
 - If used without thinking about how caching works, may give people wrong expectations (e.g. wouldn't cache anything sometimes and may even reduce performance in some edge cases)

#### Document this API instead of actually adding it
Can even go as far as doing all the code that you would PR to this repository, but then converting it to docs.

##### Pros:
 - No need to maintain new APIs
 - Responsibility for such implementation is on users, not maintainers

##### Cons:
 - Won't give users a painless way to cache elemental blocks
 - We would still have to maintain the documentation (documentation complexity increases)
 - We still won't be able to implement caching in blocks consistently

#### Implement more generic API in the framework
Such a generic feature would be supported by other framework components (e.g. SSViewer) and would allow more transparent caching and cache invalidation.

##### Pros:
 - More generic and flexible
 - Would allow integration with other framework components (e.g. View, Middlewares)

##### Cons:
 - Much more complex to implement. Requires much more investigation, planning and discussions
 - May break BC, so we'll have to wait next major release (CMS 5) to ship that
 - For blocks it's not much different with what exact higher level API to reconcile its caching implementation. To have any actual performance benefits, the heavy-lifting still has to be implemented in the blocks.

**Comment by ScopeyNZ** [comment]
We've been talking about this in other channels, but I'm still not really keen on adding this API. I would be much more supportive of a generic API provided by Framework that allows more than just SSViewer support. As it stands, I think this is better suited as a suggestiong in documentation.

**Comment by dnsl48** [comment]
> As it stands, I think this is better suited as a suggestion in documentation.

Would you be able to give an example of such documentation? At the moment I'm not quite sure what exactly you suggest documenting there?

**Comment by ScopeyNZ** [comment]
Rather than put the API into this module, just give the API as an example:

"You might like to use an interface like (show the API as an example) to implement partial caching on blocks - see the Framework documentation (https://github.com/silverstripe/silverstripe-framework/issues/9508) for more information"

**Comment by dnsl48** [comment]
I don't see how any generic framework API can substitute proper implementations of `BaseElement::isCacheable()` and `BaseElement::getCacheKey()`. That still has to be done for every single block on case-by-case basis.

The APIs suggested in this issue would allow us to leverage existing framework features.
#### Template partial cache
```html
<% cached $ElementalArea.getCacheKey if $ElementalArea.isCacheable %>
    $ElementalArea
<% end_cached %>
```
#### HTTP cache
```php
if (!$elementalArea->isCacheable()) {
    HTTPCacheControlMiddleware::singleton()
        ->disableCache();
}
```

The alternative is to loop through the elements and depending on every single block implementation try to use its APIs, for which we don't have any conventions at the moment, so there's nothing to recommend or document in that regard.

**Comment by ScopeyNZ** [comment]
So here's my list of preference for resolution of this issue:

1) Document this approach in Elemental, with some use-cases and examples
2) Document this approach in Framework (for generic caching of `ViewableData`)
3) Add an opt-in interface that works on `ViewableData` to framework, and build in some support to SSViewer - binding objects to a cached section (in a view) that implement this interface will use the API to serve either cached or un-cached partials. Elemental can then build in some support if it needs to. RestfulServer and GraphQL can use this API too.
4) Do nothing
5) Implement this API here

Here's a Pros/Cons of this approach (IMO):

Pro:
- We're helping to prevent a footgun of caching stuff that shouldn't be cached, provided the developer knows how to implement these methods properly

Cons:
- It's a complicated concept that we'll need to heavily document and probably field a bunch of questions
- The API doesn't actually do anything without expressly catering for it in your own code
- The proposal API is abstract (or void) methods on some already complicated models - and is conflating their responsibilities
- We're strongly assuming that caching is a generic "this can be cached, this can't" when it comes to different cache interfaces, and this is not true

To expand on that last point a little; your example of using the API in HTTP cache and template partial cache is potentially incorrect. There's definitely things that I would be happy to send HTTP cache headers for, but not have partial caching for, and vice versa. We can't just assume peoples caching use cases.

Given that each project has different caching requirements, different systems in place for caching, and will probably require a fair amount of _custom_ business logic to be implemented properly, I don't think it should be our duty to try to provide a one-size-fits-all solution.

**Comment by dnsl48** [comment]
> 1. Document this approach in Elemental, with some use-cases and examples

Sorry, I still don't completely understand what approach you suggest documenting? AFAIK, we don't even have any conventions around how to cache blocks, neither any API.

> Add an opt-in interface that works on ViewableData to framework, and build in some support to SSViewer - binding objects to a cached section (in a view) that implement this interface will use the API to serve either cached or un-cached partials

I guess implementation of extra features for the framework might be worth discussing separately in the framework repo. In this issue I'm merely suggesting to leverage features framework already provides for caching. I have to say that I like this idea, in general. However, it's too raw at this point and requires much more thinking. We cannot just toss in a new interface in the framework, there's not much reason for it without reworking lots of other subsystems that would work with that interface. This might require a potential rework of some features and may be impossible to do without breaking stuff. Even if we work in that direction, realistically that doesn't feel like we'll have it delivered before CMS 5.

> 4. Do nothing
5. Implement this API here

My opinion is the opposite. I reckon this API is much better than nothing. However, I might miss something? Otherwise, I don't see any good ways to cache ElementalArea without this new API.

> Cons:
> * It's a complicated concept that we'll need to heavily document and probably field a bunch of questions
>  * The API doesn't actually do anything without expressly catering for it in your own code
> * The proposal API is abstract (or void) methods on some already complicated models - and is conflating their responsibilities

These are same, even if we add new fancy features to the framework. Doesn't make any difference.

> We're strongly assuming that caching is a generic "this can be cached, this can't" when it comes to different cache interfaces, and this is not true
> your example of using the API in HTTP cache and template partial cache is potentially incorrect. There's definitely things that I would be happy to send HTTP cache headers for, but not have partial caching for, and vice versa. We can't just assume peoples caching use cases.

If you have blocks with unique cache behaviours for different cache types, I don't think we should provide any generic APIs for that. The block should provide its own API for its own edge case. Same, it would be wrong to try solving that edge case in the framework by some generic interfaces.

> I don't think it should be our duty to try to provide a one-size-fits-all solution

Fair enough. That's why I suggest the new API to be opt-in. Two methods are a simple convention which could cover most of the use cases. That convention with safe defaults can help a vast number of applications. The ones with more tricky requirements will have to come up with custom ad hoc solutions, but that's not something we could solve in the framework generically either.

**Comment by ScopeyNZ** [comment]
> Sorry, I still don't completely understand what approach you suggest documenting? AFAIK, we don't even have any conventions around how to cache blocks, neither any API.

Document the solution you want to add to the codebase instead of actually adding it. You can even go as far as doing all the code that you would PR to this repository, but then converting it to docs.

> I have to say that I like this idea, in general. However, it's too raw at this point and requires much more thinking.

So this is kind of the point I'm making. I don't like introducing half-baked APIs in place of something that could have a more fully-fledged solution.

> My opinion is the opposite. I reckon this API is much better than nothing. However, I might miss something? Otherwise, I don't see any good ways to cache ElementalArea without this new API.

I agree it's better than nothing - however the impact of adding API can never be forgotten in a big complicated product like SilverStripe - especially with such a small committed team of contributors. I'm not saying the API is worse than nothing, but I'm saying it's not worth the increased effort to support and maintain. Note that I feel strongly in this case as caching is really hard, and more likely to result in questions, bug reports, and general support.

> These are same, even if we add new fancy features to the framework. Doesn't make any difference.

The framework suggestion I had actually did have an immediate effect once you implement the interface if we add in-build SSViewer support for it. This suggestion requires implementing the new interface, and then also updating the code to consume it. 

I don't really agree those 3 points are the same.

> The block should provide its own API for its own edge case. Same, it would be wrong to try solving that edge case in the framework by some generic interfaces.

Yes. Let's just suggest ways that developers could approach these edge cases, maybe by adding some API to BaseElement/ElementalArea.

> Fair enough. That's why I suggest the new API to be opt-in. Two methods are a simple convention which could cover most of the use cases. That convention with safe defaults can help a vast number of applications. The ones with more tricky requirements will have to come up with custom ad hoc solutions, but that's not something we could solve in the framework generically either.

So I think the main misunderstanding here is that I'm concerned about increasing our API from a maintainability point of view, and I think you're just focussed on providing any possible solution, while not considering effort to maintain as a factor. Correct me if I'm wrong here.

There's a very simple way to avoid increasing API while helping to solve the problem, and that is to provide suggestions and examples in docs, which is what I've been harping on about this whole time. We can just provide these two methods as a *suggestion/example* rather than actually adding it to our API. "Hey, if you cache stuff this example might help you cache properly!"

**Comment by dnsl48** [comment]
> I don't like introducing half-baked APIs in place of something that could have a more fully-fledged solution.

I don't believe we can have a more fully-fledged solution (unless until CMS5). I also disagree this would be a half-baked API. It can provide good and safe defaults and some conventions to start working on caching in blocks. Eventually, even if we find later that the initial API may be more optimal, it would be much easier to refactor here rather than in the framework.

---
> Document the solution you want to add to the codebase instead of actually adding it. You can even go as far as doing all the code that you would PR to this repository, but then converting it to docs.

I see, makes sense. However, I don't think that would work.
The API aims to provide not only safe default implementations but also some conventions for implementing caching strategies in blocks. Eventually, proper caching has to be implemented in blocks regardless of where the higher level API lives. Would it be framework or elemental module, does not matter for the block, but we need some APIs or conventions for that. It's not optimal to do it randomly and differently in every block, relying only on documented suggestions. E.g. we cannot properly implement caching for userforms block, because there are no API and no conventions.

I guess it may be worth continue discussing when we have the PR ready and it's cleaner what the suggestion looks like exactly.

---
> So I think the main misunderstanding here is that I'm concerned about increasing our API from a maintainability point of view, and I think you're just focussed on providing any possible solution, while not considering effort to maintain as a factor. Correct me if I'm wrong here.

Yes, fair enough. I think I understand your main concerns.
I can only say I've investigated all the options mentioned above and even more.
The ones that we discussed here are
 - improve caching in the framework in a generic way
 - implement API in the elemental module
 - document caching best practices and no new APIs

And I'm convinced that API in the elemental module is the most optimal one.
Implementing it on the framework level is most likely not achievable without breaking backward compatibility. Not providing any APIs prevents us from shipping any caching in the actual blocks. Providing new methods in elemental might increase API surface, however the default implementations are quite simple, so I don't think we'll have to be investing too much in their maintenance. Furthermore, it would be easily replaced be the discussed new framework features shall we implement them. It would also give us some conventions and APIs now, when we need them to implement caching for blocks.

That said, sorry, I cannot agree that I'm just focussed on providing any possible solution, while not considering effort to maintain as a factor :)

**Comment by ScopeyNZ** [comment]
Ok. Just so that we're completely _completely_ clear on this suggestion, I'll recap it. 

Your suggestion is:

- we implement four new methods, two each to `BaseElement` and `ElementalArea`,
- we don't declare them as abstract or part of an interface because that would be breaking,
- we don't utilise the new API in any way, 
- we document how it should be implemented

My suggestion is:

- we document a suggestion for caching that is to include four new methods, two each to `BaseElement` and `ElementalArea`,
- we document how it should be implemented

With your suggestion:

- It falls under our supported API. We get questions like "I implemented this method but it did nothing". "I've upgraded and I have a conflict with my method I added 5 years ago".
- We agree that a new API, maybe in CMS5 could replace this, which means we have to deprecate this, provide migration guides, have to potentially release a new major if there's a conflict in naming

With my suggestion:

- The documentation will probably go un-noticed by many
- There's extra effort to copy & paste the suggestion
- Developers can consider the suggestion and partially implement, or alter the implementation to suit their business needs.

------------

> Implementing it on the framework level is most likely not achievable without breaking backward compatibility

I'm not suggesting this task becomes "do it on framework", I'm just saying this is a more valuable solution on framework.

> Not providing any APIs prevents us from shipping any caching in the actual blocks.

We're not doing that anyway. We're providing API you can use to cache things yourself. You get no caching out of the box with this new API

> Providing new methods in elemental might increase API surface, however the default implementations are quite simple, so I don't think we'll have to be investing too much in their maintenance.

Questions about implementation, deprecating it in the future, fielding PRs that utilise the API - these are all points where our input is required, by adding this "simple" API. Complexity of the API is only one factor on whether this requires maintenance. Other factors are likelihood of use (to be clear, my opinion here is "quite unlikely") and complexity of the complex - which is my main stinging point - I'd say it's "very high"

> Furthermore, it would be easily replaced be the discussed new framework features shall we implement them.

That makes this a maintenance burden. I really don't want to deal with a potential situation where framework's new API conflicts with the API here. Deprecations, followed by only being able to support new API in a major version, meaning the API doesn't actually appear removed, but changed it's implementation or something. Sounds like hard work.

> It would also give us some conventions and APIs now, when we need them to implement caching for blocks.

I'm happy to reconsider my stance if we actually add something that consumes this API. Until then I'm completely in the camp of "put it all in docs, don't introduce an API that isn't used by anything".

**Comment by dnsl48** [comment]
> Ok. Just so that we're completely completely clear on this suggestion, I'll recap it.

Yes, nice recap! Thank you :)
I'd also add one more item there `With API suggestion: we can implement caching in blocks and use it in a consistent and generic manner`, `With NO API suggestion: we cannot implement caching in blocks, neither use it in a consistent way`.

---

> We agree that a new API, maybe in CMS5 could replace this, which means we have to deprecate this, provide migration guides

I'd say this is really THIN API. I reckon most of the effort would go into aligning the actual block caching implementations with the new or old framework caching APIs. Here we could have an extra step towards making blocks implement it more consistently before we ship something huge in the framework.

---
> Complexity of the API is only one factor on whether this requires maintenance. Questions about implementation, deprecating it in the future, fielding PRs that utilise the API - these are all points where our input is required, by adding this "simple" API

1. IMHO, lack of this API actually makes it much harder to answer those questions
2. this is supposed to be opt-in, so users should still be able to use their own caching implementations
3. I agree that we don't have support what does not exist. However, I reckon caching is a feature worth existing

---
> I'm happy to reconsider my stance if we actually add something that consumes this API

I guess that's the plan, to start using this block in blocks. Without this API I don't see a how we can do anything consistent in blocks.

**Comment by ScopeyNZ** [comment]
> I'd also add one more item there With API suggestion: we can implement caching in blocks and use it in a consistent and generic manner

My point is that we're not doing that, so it doesn't make sense to add that to the list. We don't provide caching out of box anywhere in this module, and adding it is another discussion.

> 1) IMHO, lack of this API actually makes it much harder to answer those questions

My point is the questions won't be asked, or it doesn't really fall without our responsibilities to answer questions about a suggestion/example provided in docs versus one asked about actual code in our module

> 2) this is supposed to be opt-in, so users should still be able to use their own caching implementations

Again, my point is that because they have to be "power-users" to do this anyway, don't add code, just add docs.

> 3) I agree that we don't have support what does not exist. However, I reckon caching is a feature worth existing

Only if we actually make it do something OOTB...

Frankly, I feel like we've reached an impasse. Neither of us seem to get each others point. I'm still going to be actively against a PR that introduces this API at this point, for the reasons I've stated. I think we need somebody else from the team to come weigh in their opinions.

**Comment by dnsl48** [comment]
> Frankly, I feel like we've reached an impasse. Neither of us seem to get each others point

Not at all! I think we both made our thoughts clear enough and I hope we both understood others' points well. Now, I reckon we should agree to disagree. When the PR is ready, we can invite others to tell their thoughts and discuss it further. Potentially I guess this may end up with a vote.
Thank you for caring and spending time on this lengthy discussions @ScopeyNZ! :)

**Comment by dnsl48** [comment]
@ScopeyNZ I've tried to summarize our discussion in the header (`Discussion points`).
Please have a look if I missed anything?
When we have the summary ready, I think we could invite others to chime in.
The PR is currently in a PoC state, but I don't think the method signatures would change.
IF we decide to add it, then I'll add documentation to it later. If we decide to ditch it, then no point to spend time on it anyway.

**Comment by ScopeyNZ** [comment]
Yep that summary looks fine.

**Comment by dnsl48** [comment]
`Discussion points` section in the head of this issue summarizes the points from the discussion above.

---

@silverstripe/core-team please cast your vote (this is the `Option I` from [the issue 83](https://github.com/silverstripe-security/security-issues/issues/83))

#### Option A (:smile:) : Already good enough (do nothing, leave as is)

* Our recommendation is "do not cache ElementalArea"
  * OR, extend ElementalArea and implement your own caching in your app
* Every block should cache itself
* Every block may or may not provide different ad-hoc caching APIs

#### Option B (:eyes:) : Documentation only

 * Same as Option A
 * We write some extra documentation to explain how that custom caching implementation might look like

#### Option C (:tada:) : Ship the new API
 * New generic way to cache ElementalArea
 * Introduce the convention for all blocks to implement caching consistently
 * Opt-in and mostly backward compatible
 * Every block is still responsible for shipping its caching

#### Option D (:rocket:) : Let us find another way
 * Same as `Option A`
 * Keep looking for better options (e.g. come up with a more generic and flexible approach for caching in framework)

**Comment by robbieaverill** [comment]
Option D sounds more like option C to me, and I would say that my preference would be that whatever you do in this module is consuming a framework API. We should treat elemental as an implementation example of our framework and not come up with too many random APIs that are unique to this module.

My vote is option A. I assume this has all come up due to a lack of documentation or something, so if more docs are needed then that's fine, but I'd probably expect those docs to resolve around partial cache keys in templates rather than PHP APIs in docs, unless those APIs exist in framework and are just implemented here.

**Comment by dnsl48** [comment]
> I assume this has all come up due to a lack of documentation or something, so if more docs are needed then that's fine, but I'd probably expect those docs to resolve around partial cache keys in templates rather than PHP APIs in docs

That's really about `avoid caching ElementalArea, or implement your own caching in PHP`. Currently there is nothing consistent we can use to cache it in templates or with HTTPCacheControl middlewares.

**Comment by ScopeyNZ** [comment]
I split my vote across A and B. Read the rest of this issue for my reasoning 😂

**Comment by kinglozzer** [comment]
I’m going for option A, because IMO the generation of complex cache keys is where core partial caching falls down. E.g. how do you efficiently generate a cache key that will change when a `many_many` relation has been re-ordered? Even assuming a re-order updates the `LastEdited` date of related items, it’s still an unnecessary database query to get that value.

Personally, I’ve long since given up on partial caching and instead use https://github.com/heyday/silverstripe-cacheinclude, which invalidates caches on DataObject write instead.

**Comment by ChrissiQ** [comment]
Hey guys, so I'm the one who submitted the issue that sparked this one.  The problem we had was that it was non-obvious that we should not cache `$ElementalArea`, so we did.  All one has to do is install https://github.com/dnadesign/silverstripe-elemental-userforms while having cached elemental areas and immediately you've got the potential for catastrophe.

I'm perfectly happy with option A (obviously it'd be great to have an API for elemental block cache-ability, but it's not strictly necessary), but the documentation will have to be **prominent** enough so that devs who are wondering about security/caching elemental blocks will be sure to see it. I think it's very easy for devs to miss the issue - for one thing, we assume that installed modules are going to work properly and we don't see any warnings about this when implementing caching or adding elemental blocks.  Good documentation will be plenty good enough though.

Thanks for the response to the issue, I'm glad it's getting looked at.

**Comment by ScopeyNZ** [comment]
Thanks @ChrissiQ . The documentation that we're planning to add will be on framework, but we can follow up with a mention of those new docs in this module too.

Here's the issue that tracks the docs being added to framework FYI: https://github.com/silverstripe/silverstripe-framework/issues/9508

**Comment by dnsl48** [comment]
Thanks to everyone involved for your time and thoughts!
Looks like we all agree that this feature is redundant and we should concentrate on providing better documentation with guidelines and best practices, rather than try to solve this on the API level.

We will continue the work on the partial template caching documentation in https://github.com/silverstripe/silverstripe-framework/issues/9508

**Comment by chillu** [comment]
Thanks for getting back to us here @ChrissiQ, and for sending such a comprehensive issue report! You're actually only seeing the tip of the iceberg on this discussion, there's another 50+ comments in an internal security issue. So it's definitely got a few people thinking here. Turns out caching is hard ;)
