### ISSUE TITLE
Remove reliance on silverstripe-widgets?

### ISSUE THREAD

**Issue by chillu** [dnadesign/silverstripe-elemental#81]
I'm wondering if this module could be simplified if we use `Element` as the base class, and remove the reliance on [silverstripe-widgets](https://github.com/silverstripe/silverstripe-widgets). I see `Element` as a better alternative to `Widget`. 

Or put another way, I don't see how the widgets module should be used other than in a mature content blocks solution. The portal-style "sidebar" functionality that widgets was originally developed for has been replaced by responsive design which treats content as linear sequences of content. These sequences can sit side-by-side in more complex designs, but they're not arranged in a "sidebar" widget area next to content coming from the page type, they *are* the content. 

 * The mixed terminology between "widget" and "element" is confusing to developers
 * Having a "base module" makes API changes and release planning harder
 * The `Title`, `Sort` and `Enabled` fields could be migrated from `Widget` (simlar for `WidgetArea`)
 * [WidgetAreaEditor](https://github.com/silverstripe/silverstripe-widgets/blob/master/src/Forms/WidgetAreaEditor.php) and [WidgetPageExtension](https://github.com/silverstripe/silverstripe-widgets/blob/master/src/Extensions/WidgetPageExtension.php) don't seem to be used, and is a large part of the "surface area" of the widgets module
 * It already removes the [WidgetContentControllerExtension](https://github.com/silverstripe/silverstripe-widgets/blob/master/src/Controllers/WidgetContentControllerExtension.php)
 * There's not a lot of other [dependents](https://packagist.org/packages/silverstripe/widgets/dependents) on the widgets module which are in widespread use
 * Only [two of twelve content blocks modules](https://docs.google.com/document/d/1hffZFknysYi6tp55eOk4DzON4pjoEt7Xq4GGD-ZGah0/edit) have decided to build on top of widgets

**Comment by wilr** [comment]
Totally Ingo, building on top of widget is probably outdated so no real reason to do it that way and redundant in 2017. It also makes the template logic a bit messy with Areas, Holders and Template. I think last time myself and John spoke we knew SS Ltd was going to support a content block officially so held off any major changes

**Comment by pitchandtone** [comment]
There's a bunch of reasons wy the widgets architecture has some good things
which even if we remove the dependancy we'd need to move into Element /
Element Area

1) Widget and Controller relationship is required for handling forms, other
modules have re-implemented this in a very similar way (e.g.
https://github.com/sheadawson/silverstripe-blocks/blob/master/src/controllers/BlockController.php
)
2) WidgetHolder rendering vs WidgetContent is helpful so that it's easy to
have consistent HTML wrappers on every element, I disagree with Will on
this point, I think it's a feature.
3) WidgetAreas are helpful to render widgets and maintain relationships
easier than a many_many. It also opens the door to having multiple areas on
one page, whereas many_many causes issues here and has to be hacked around
using things like 'areas'

**Comment by pitchandtone** [comment]
In progress on the SS4 branch.

**Comment by pitchandtone** [comment]
Seems to be working well on the SS4 branch, now need to https://github.com/dnadesign/silverstripe-elemental/issues/97
