### ISSUE TITLE
BUG: Add Element Popover font icons

### ISSUE THREAD

**Issue by a2nt** [dnadesign/silverstripe-elemental#864]
Add Element Popover will look bad using custom font icons

For example when you add fontawesome requirement to the CMS and define an icon using font awesome class it will break font styling of the element at the pop over.
```
class MapCategoryElement extends BaseElement
{
    private static $icon = 'fas fa-map-signs';
}
```
![Screenshot from 2021-01-13 15-31-50](https://user-images.githubusercontent.com/672794/104455655-311abf00-55da-11eb-812e-12d1102683e4.png)

It works bad cuz icon class being applied to whole element button tag including element name. 
I suggest to use an other tag for the icon inside button tag content

**Comment by Cheddam** [comment]
Hi @a2nt, thanks for raising this issue!

Elemental's UI is specifically designed to work with the built-in Silverstripe CMS icon library, which last year received a range of new block-specific icons that might cover your use case. You can see the full list of icons included as of the latest Silverstripe CMS release [here](https://silverstripe.github.io/silverstripe-admin/?selectedKind=Admin%2FIcons&selectedStory=Icon%20reference&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel).

If you'd like the ability to add custom icons in this way, I'd encourage you to raise a pull request that introduces this in a non-breaking way. For now, since this is an enhancement rather than a bug, I'll close it out per our [contribution guidelines](https://docs.silverstripe.org/en/4/contributing/issues_and_bugs/#feature-requests).
