### ISSUE TITLE
BaseElement::getGraphQLTypeName() must be of the type string, null returned

### ISSUE THREAD

**Issue by emteknetnz** [dnadesign/silverstripe-elemental#875]
https://travis-ci.org/github/dnadesign/silverstripe-elemental/jobs/758628526

GraphQL 4 - dev-master 56424b3

Core issues seems to be that the following returns null, instead of a string.  TestElement implements TestOnly

`Schema::create('admin')->getTypeNameForClass("DNADesign\Elemental\Tests\Src\TestElement")`

**Comment by unclecheese** [comment]
Ok there are a few things going on here:

`getGraphQLTypeName()` relies on stored schema state. It reads the context object stored as generated code on the webserver.  Most of the time this is fine, because it's hard to get access to an area of the CMS that isn't defended by the autobuild procedure in the GraphQL controller. Tests are an exception to this.

Should getters rely on schema state? Probably not.

We could have the getter fallback on booting the schema (creating it without using the stored state) and reading the context off that. That would be slow, and presents a potential performance trap in what should be a simple getter in `BaseElement`.  

So the way we can solve this is by creating a stub for `SchemaBuilder` that never reads from the code gen. It just always boots and manages its own cache, ensuring there are never any code gen side effects for basic unit tests that don't relate directly to GraphQL. Test like this one would simply call `NaiveSchemaBuilder::activate()` in their setup, which would basically block any reliance on code gen and do everything in memory. Seems like a good idea.

But wait! We have another problem. There's a circular dependency here. Booting the BaseElement model means resolving the `blockSchema` field, _which requires getGraphQLTypeName()_ (in the custom `typeName` field). Yikes!

Why is BaseElement using this anti-pattern of shimming its own `typeName` field, when `_typename` is given out of the box by Apollo? It seems like this has already been considered and raised as a concern: https://github.com/dnadesign/silverstripe-elemental/blob/4/client/src/components/ElementEditor/AddElementPopover.js#L34

## Suggested fix

* Create a `NaiveSchemaBuilder` for tests like this that just need to say, "Hey, graphql, shut up for a sec" (Done here: https://github.com/silverstripe/silverstripe-graphql/pull/352/commits/4afb7d5041b219358fa41078225ac2f0eae13556)

* Update Elemental to use `__typename` instead of its homespun `element.typeName` attribute. (updates to three or four files)

Any objections? Particularly to using `__typename` over `typeName`?

**Comment by emteknetnz** [comment]
Would changing typeName to __typename break graphql 3 functionality?  If so does this mean that we'd need to do a conditional statement within elemental to use the correct key depending on which version of graphql is installed?

**Comment by unclecheese** [comment]
`__typename` is a GraphQL standard. It's provided by the thirdparty graphql-php module we're using, I think. If not, Apollo definitely will fill it in for us. So it should be the same across versions.

**Comment by emteknetnz** [comment]
Duplicate https://github.com/silverstripe/silverstripe-graphql/issues/354, closing issue
